# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dtpvn1XzsWvZYrZ2jYO4P5Lkvaegvhit

Primero que todo trataré de instalar Plotly
"""

pip install plotly

"""

```
# Esto tiene formato de código
```

"""

import plotly.express as px

# Datos
dias_semana = ["Viernes", "Sábado", "Domingo", "Lunes", "Martes", "Miércoles", "Jueves"]
calorias_almuerzo = [650, 700, 1000, 1100, 800, 550, 650]

# Crear un DataFrame a partir de los datos
import pandas as pd
df = pd.DataFrame({'Día de la semana': dias_semana, 'Calorías en el Almuerzo': calorias_almuerzo})

# Crear el gráfico de barras
fig = px.bar(df, x='Día de la semana', y='Calorías en el Almuerzo', title='Calorias que consumo en el amuerzo por día')

# Mostrar el gráfico
fig.show()

"""Ahora un poco más personalizado"""

import plotly.express as px

# Datos
dias_semana = ["Viernes", "Sábado", "Domingo", "Lunes", "Martes", "Miércoles", "Jueves"]
calorias_almuerzo = [650, 700, 1000, 1100, 800, 550, 650]

# Crear un DataFrame a partir de los datos
import pandas as pd
df = pd.DataFrame({'Día de la semana': dias_semana, 'Calorías en el Almuerzo': calorias_almuerzo})

# Crear el gráfico de barras
fig = px.bar(df, x='Día de la semana', y='Calorías en el Almuerzo', title='Calorias que consumo en el amuerzo por día')

# Cambiar el tamaño, la fuente, el color y centrar el título
fig.update_layout(
    title_text='Consumo de Calorías en el Almuerzo',
    title_font=dict(size=48, color='Pink', family='Times New Roman'),
    title_x=0.5  # Centro horizontalmente el título
)

# Mostrar el gráfico
fig.show()

"""Ahora trataré de cambiar colores de barras"""

import plotly.express as px

# Datos
dias_semana = ["Viernes", "Sábado", "Domingo", "Lunes", "Martes", "Miércoles", "Jueves"]
calorias_almuerzo = [650, 700, 1000, 1100, 800, 550, 650]

# Crear un DataFrame a partir de los datos
import pandas as pd
df = pd.DataFrame({'Día de la semana': dias_semana, 'Calorías en el Almuerzo': calorias_almuerzo})

# Crear el gráfico de barras con todas las barras en color 'fuchsia'
fig = px.bar(df, x='Día de la semana', y='Calorías en el Almuerzo', title='Calorias que consumo en el almuerzo por día', color_discrete_sequence=['fuchsia'])

# Cambiar el tamaño, la fuente y centrar el título
fig.update_layout(
    title_text='Consumo de Calorías en el Almuerzo',
    title_font=dict(size=48, color='Pink', family='Times New Roman'),
    title_x=0.5  # Centro horizontalmente el título
)

# Mostrar el gráfico
fig.show()

"""Diferenciar los días que como más de 1000 calorias en el almuerzo"""

import plotly.graph_objects as go

# Datos
dias_semana = ["Viernes", "Sábado", "Domingo", "Lunes", "Martes", "Miércoles", "Jueves"]
calorias_almuerzo = [650, 700, 1000, 1100, 800, 550, 650]

# Crear un DataFrame a partir de los datos
import pandas as pd
df = pd.DataFrame({'Día de la semana': dias_semana, 'Calorías en el Almuerzo': calorias_almuerzo})

# Crear una figura de barras
fig = go.Figure()

for index, row in df.iterrows():
    color = 'blue' if row['Calorías en el Almuerzo'] > 999 else 'fuchsia'
    fig.add_trace(go.Bar(x=[row['Día de la semana']], y=[row['Calorías en el Almuerzo']], text=[row['Calorías en el Almuerzo']],
                marker_color=color, name=''))

# Personalizar el título
fig.update_layout(
    title='Calorías que consumo en el almuerzo por día',
    title_font=dict(size=50, color='Pink', family='Times New Roman'),
    title_x=0.5  # Centro horizontalmente el título
)

# Mostrar el gráfico
fig.show()

"""Borramos los cuadritos de etiqueta, que no sé en que momento de pusieron."""

import plotly.graph_objects as go

# Datos
dias_semana = ["Viernes", "Sábado", "Domingo", "Lunes", "Martes", "Miércoles", "Jueves"]
calorias_almuerzo = [650, 700, 1000, 1100, 800, 550, 650]

# Crear un DataFrame a partir de los datos
import pandas as pd
df = pd.DataFrame({'Día de la semana': dias_semana, 'Calorías en el Almuerzo': calorias_almuerzo})

# Crear una figura de barras sin leyenda
fig = go.Figure()

for index, row in df.iterrows():
    color = 'blue' if row['Calorías en el Almuerzo'] > 999 else 'fuchsia'
    fig.add_trace(go.Bar(x=[row['Día de la semana']], y=[row['Calorías en el Almuerzo']], text=[row['Calorías en el Almuerzo']],
                marker_color=color, name=''))

# Personalizar el título
fig.update_layout(
    title='Calorías que consumo en el almuerzo por día',
    title_font=dict(size=50, color='Pink', family='Times New Roman'),
    title_x=0.5,  # Centro horizontalmente el título
    showlegend=False  # Ocultar la leyenda
)

# Mostrar el gráfico
fig.show()

"""Ahora con la tabla completa, un gráfico diferente, un codigo que pillé interesante y veré si puedo adaptar

"""

import plotly.express as px
import pandas as pd

# Datos
data = [
    ["Viernes 06/10/23", "Sí", 300, 650, 700, 1],
    ["Sabado 07/10/23", "Sí", 260, 700, 550, 2],
    ["Domingo 08/10/23", "No", 0, 1000, 650, 2],
    ["Lunes 09/10/23", "No", 0, 1100, 650, 1],
    ["Martes 10/10/23", "Sí", 400, 800, 300, 1],
    ["Miércoles 11/10/23", "Sí", 450, 550, 500, 1],
    ["Jueves 12/10/23", "Sí", 550, 650, 600, 2]
]

columns = ["día", "Tomó desayuno", "Desayuno (Cal)", "Almuerzo (Cal)", "Cena (Cal)", "Agua Litros"]

df = pd.DataFrame(data, columns=columns)

# Crear el gráfico de burbujas estático con tamaños y colores personalizados
fig = px.scatter(df, x="día", y="Almuerzo (Cal)", size="Almuerzo (Cal)",
                 color="Tomó desayuno", color_discrete_sequence=["pink", "lightseagreen"],
                 labels={"día": "día", "Almuerzo (Cal)": "Calorías en el Almuerzo"},
                 title="Calorías en el Almuerzo por Día")

# Personalizar el título
fig.update_layout(
    title_text='Calorías en el Almuerzo por Día',
    title_font=dict(size=50, color='Skyblue'),  # Cambiar el tamaño y color del título
    xaxis_title="día",
    yaxis_title="Calorías en el Almuerzo",
    title_x=0.5,  # Centro horizontalmente el título ,
    showlegend=False
)

fig.show()

"""Gráfico por tamaño con toda mi tabla de una semana de habitos alimenticios, con colores diferentes si tomé desayuno o no, y forma diferente si es que tomé 2 litros de agua."""

import plotly.express as px
import pandas as pd

# Datos
data = [
    ["Viernes 06/10/23", "Sí", 300, 650, 700, 1],
    ["Sabado 07/10/23", "Sí", 260, 700, 550, 2],
    ["Domingo 08/10/23", "No", 0, 1000, 650, 2],
    ["Lunes 09/10/23", "No", 0, 1100, 650, 1],
    ["Martes 10/10/23", "Sí", 400, 800, 300, 1],
    ["Miércoles 11/10/23", "Sí", 450, 550, 500, 1],
    ["Jueves 12/10/23", "Sí", 550, 650, 600, 2]
]

columns = ["día", "Tomó desayuno", "Desayuno (Cal)", "Almuerzo (Cal)", "Cena (Cal)", "Agua Litros"]

df = pd.DataFrame(data, columns=columns)

# Crear el gráfico de burbujas con condiciones
fig = px.scatter(df, x="día", y="Almuerzo (Cal)", size="Almuerzo (Cal)",
                 color="Tomó desayuno", color_discrete_sequence=["pink", "lightseagreen"],
                 symbol="Agua Litros",  # Utilizar el símbolo para indicar si se tomó agua
                 labels={"día": "Día", "Almuerzo (Cal)": "Calorías en el Almuerzo"},
                 title="Calorías en el Almuerzo por Día")

# Personalizar el título
fig.update_layout(
    title_text='Calorías en el Almuerzo por Día',
    title_font=dict(size=50, color='Skyblue'),  # Cambiar el tamaño y color del título
    xaxis_title="Día",
    yaxis_title="Calorías en el Almuerzo",
    title_x=0.5,  # Centro horizontalmente el título
    showlegend=False
)

fig.show()