# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19XivBbQhZZachYFEdLmK1cwZsx7zL1Cd

# Problema 1.
## Hacer un programa que imprima los números del 1 al 100.
"""

for numero in range(1, 101):
    print(numero)

"""# Problema 2
Hacer un programa que imprima los números del 1 al 100 que sean divisibles entre 3 (con resto 0)

Esto signifca que si el número es 3, 6, 9, 12, 15, etc. entonces debe imprimirlo ya que la división de esos números por 3 da como resto 0, exacto.
"""

for x in range(100):

  if (x+1) % 3 == 0:
    print(x+1)

"""# Ejercicio de practica promedios"""

# Calcular la nota final de un estudiante teniendo en cuanta que:
# la primera nota vale 30% de la nota final
# la segunda vale 30% de la nota final
# y el trabajo final vale 40% de la nota final


nota_1 = float (input ("ingresa la n1"))
nota_2 = float (input ("ingresa la n2"))
nota_3 = float (input ("ingresa la n3"))
ponderacion = (nota_1 * 0.3) + nota_2 * 0.3 + nota_3 * 0.4

print(ponderacion)

if(ponderacion>=4) :
  print("APROBASTE!")
elif(ponderacion<4) :
  print("REPROBASTE!")
else:
  print("ERROR")

"""
# Problema 3.
Pseudocódigo, Sumador y comparador de dos números Realiza el algoritmo para un sumador de dos números. Si el resultado es menor a 100 se mostrará el mensaje "menor a 100", si el resultado es mayor a 100, pero menor a 150 mostrará el mensaje "mayor a 100", pero si es mayor a 150 mostrará el mensaje "mayor a 150".



"""

numero_1 = int(input("Ingresa un número"))
numero_2 = 5
suma = numero_1 + numero_2
resultado = ""

if(suma<100):
  resultado = "menor a 100"
elif(suma>=100 and suma<150):
  resultado = "mayor a 150"
elif(suma>=150):
  resultado = "mayor a 150"

print(resultado)

"""# Problema 4.
Pseudocódigo, Calculador de promedio
Generar un programa que combine variables, tipos de datos y una condicional en Python (hacer una función que evalúe si el usuario es mayor de edad y si le gusta la programación, que envíe diferentes textos según la respuesta del usuario)

"""

# Preguntar la edad al usuario y si le gusta programar
edad = int(input("¿Cuál es tu edad? "))
gusta_programar = input("¿Te gusta programar? (Sí/No) ")

if edad >= 18 and gusta_programar == "sí":
    promedio = "Eres mayor de edad y sí te gusta programar."
elif edad >= 18 or gusta_programar == "sí":
    promedio = "Eres mayor de edad o sí te gusta programar."
else:
    promedio = "Eres menor de edad o no te gusta programar."

print(promedio)